# Generated by Django 4.1.5 on 2023-01-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='top',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
