# Generated by Django 4.1.5 on 2023-01-23 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='top',
        ),
    ]
