# Generated by Django 2.2.3 on 2023-01-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Cliente',
        ),
    ]
