# Generated by Django 2.2.3 on 2023-01-11 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20230111_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='data_criacao',
            new_name='data',
        ),
    ]
